/* eslint-disable no-restricted-globals */
import handlebars from 'handlebars';
import helpers from 'handlebars-helpers';

import config from '../../config/environment';
import HtmlReports from './htmlReports';
import HandlebarsEmailTemplate from './templates/handlebarsEmailTemplate';
import { isUndefined, isGreaterThan, isLessThan, isBetween } from './templates/handlebarHelpers';

/**
 * this helper checks (in accordance with the way handlebars works) for the
 * final 'else' condition for showPercentage in fireTurnoutDurationPercentile90 &
 * emsTurnoutDurationPercentile90
 */
handlebars.registerHelper('isUndefined', isUndefined);

/**
 * this helper checks (in accordance with the way handlebars works) if the first
 * parameter is greater than the second
 */
handlebars.registerHelper('isGreaterThan', isGreaterThan);

/**
 * this helper checks (in accordance with the way handlebars works) if the first
 * parameter is less than the second
 */
handlebars.registerHelper('isLessThan', isLessThan);

/**
 * this helper checks (in accordance with the way handlebars works) if the first
 * parameter is between the second and third
 */
handlebars.registerHelper('isBetween', isBetween);

/**
 * This initializes the handlebars-helpers imported on line 2. handlebars-helpers gives us access
 * to a wider palette of operators to use in templates. for example, in agencyIncidentTypeSummary.hbs
 * you can see that we use the #compare operator on line 61
 */
helpers({ handlebars });

/**
 * Generates html, using the shell template and partials, given a set of
 * mergeVars
 * mergeVars should be an array of objects generated by the sections. see server/lib/emails/sections
 * @param {*} mergeVars
 */
export default function getEmailHtml(mergeVars) {
  const htmlReports = new HtmlReports(new HandlebarsEmailTemplate(
    handlebars,
    config.mailSettings.emailShellCustomTemplatePath,
    config.mailSettings.emailPartialsTemplatePath,
  ).template());
  return htmlReports.report(mergeVars);
}
